MAE-173: Add a dummy payment processor when extension is installed
compucorp/uk.co.compucorp.membershipextrasdefaultconfig pull request #3
Opened 2019-12-25 12:51 UTC by nishant-bhorodia

**Overview**
Create a dummy payment processor when membershipextrasdefaultconfig extension is installed.

**Before**
No dummy payment processor was created when extension was installed.

**After**
A new dummy payment processor with name "Test Payment Processor" will be created (if it doesnt exist) during installation.

**Technical Steps**
Added a setup class named: _CreateDummyPaymentProcessorStep_ which first checks if the  payment processor with same name exists. If it doesnt exist, it creates the payment processor.
_Please note that two entries need to be made for creating a payment processor, one with is_test = 0 and another with is_test =  1 (which means with live details)._

2019-12-25 13:00 UTC, omarabuhussein requested changes

2019-12-25 13:00 UTC, omarabuhussein commented on CRM/Membershipextrasdefaultconfig/Setup/CreateDummyPaymentProcessorStep.php
> +   * This is called inside public function install of
no need for this docblock

2019-12-25 13:31 UTC, nishant-bhorodia commented on CRM/Membershipextrasdefaultconfig/Setup/CreateDummyPaymentProcessorStep.php
> +   * This is called inside public function install of
Removed it.

2019-12-25 14:12 UTC, omarabuhussein requested changes

2019-12-25 14:12 UTC, omarabuhussein commented on CRM/Membershipextrasdefaultconfig/Setup/CreateDummyPaymentProcessorStep.php
> +    // create entry with test details.
there is no need for this inline comment

2019-12-25 14:12 UTC, omarabuhussein commented on CRM/Membershipextrasdefaultconfig/Setup/CreateDummyPaymentProcessorStep.php
> +    // create entry with live details.
here too, no need for it

2019-12-26 09:44 UTC, omarabuhussein approved these changes

2019-12-26 09:45 UTC, merged